version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - surch-network

  backend:
    build: ../backend
    container_name: backend
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "5000:5000"
    networks:
      - surch-network

  frontend:
    build: ../frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - surch-network

volumes:
  elastic_data:

networks:
  surch-network:
    driver: bridge
