apiVersion: apps/v1
kind: Deployment
metadata:
  name: surch-search-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 5000
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 3000
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
          ports:
            - containerPort: 9200
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
